version: v1
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: .*/assets/
  static_dir: github.com/tgreiser/victr/app/assets
  application_readable: true

- url: .*/themes/
  static_dir: themes
  application_readable: true

- url: /.*
  script: _go_app
